name: Experiment

on:
  push:
    branches:
      - main
      
  workflow_dispatch:
  
env:
  IMAGE_NAME: ghcr.io/$(echo ${{ github.repository }} | tr '[A-Z]' '[a-z]')

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display IMAGE_NAME
        run: echo $IMAGE_NAME
